package micro_processor;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krrishdholakia
 */
public class EducateX1v1 extends javax.swing.JFrame {

    /**
     * Creates new form EducateX1v1
     */
    public EducateX1v1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Topic_Question_Txt_Fld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Topic_Area_Summary_Txt_Fld = new javax.swing.JTextArea();
        Done_Btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tag_Item_Cmb_Bx = new javax.swing.JComboBox<String>();
        Add_Tag_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Topic_Question_Txt_Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topic_Question_Txt_FldActionPerformed(evt);
            }
        });

        jLabel1.setText("Topic Question");

        jLabel2.setText("Topic Area Summary");

        Topic_Area_Summary_Txt_Fld.setColumns(20);
        Topic_Area_Summary_Txt_Fld.setRows(5);
        jScrollPane1.setViewportView(Topic_Area_Summary_Txt_Fld);

        Done_Btn.setText("Done");
        Done_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Done_BtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Insert Tag");

        Tag_Item_Cmb_Bx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Tag_Item_Cmb_Bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tag_Item_Cmb_BxActionPerformed(evt);
            }
        });

        Add_Tag_Btn.setText("Add Tag");
        Add_Tag_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Tag_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(Topic_Question_Txt_Fld)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Add_Tag_Btn)
                                .addGap(116, 116, 116)
                                .addComponent(Done_Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(Tag_Item_Cmb_Bx, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Topic_Question_Txt_Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tag_Item_Cmb_Bx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Done_Btn)
                    .addComponent(Add_Tag_Btn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Topic_Question_Txt_FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topic_Question_Txt_FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Topic_Question_Txt_FldActionPerformed

    private void Add_Tag_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Tag_BtnActionPerformed
        // TODO add your handling code here:
        
       EducateX1v1_UI new1 = new EducateX1v1_UI();
       new1.setVisible(true);
    }//GEN-LAST:event_Add_Tag_BtnActionPerformed

    private void Tag_Item_Cmb_BxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tag_Item_Cmb_BxActionPerformed
              BufferedReader Buff_reader2 = null;
              
              Tag_Item_Cmb_Bx.removeAll();

         try {                                           
            String filer = "LoginDetails.txt";
            File file2 = new File(filer);
            Buff_reader2 = new BufferedReader(new FileReader(file2));

            String line = null;
            try {
                
                while((line = Buff_reader2.readLine()) != null)
                {
                    
                    Tag_Item_Cmb_Bx.addItem(line);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EducateX1v1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(EducateX1v1.class.getName()).log(Level.SEVERE, null, ex);
            }  
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EducateX1v1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
        
    }//GEN-LAST:event_Tag_Item_Cmb_BxActionPerformed

    private void Done_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Done_BtnActionPerformed
        // TODO add your handling code here:
        
        File file = new File("LoginDetails.txt");
        File file3 = new File(Tag_Item_Cmb_Bx.getSelectedItem().toString()+".txt");
        
        String filer = Topic_Question_Txt_Fld.getText();
        
        BufferedReader Buff_reader1 = null; 

        try {            
            
            FileWriter fileWriter2 = new FileWriter(filer+".txt",true); 
             BufferedWriter bufferedWriter2 = new BufferedWriter(fileWriter2);
                bufferedWriter2.newLine();
                bufferedWriter2.write(Topic_Question_Txt_Fld.getText());
                             bufferedWriter2.close();

                
                FileWriter fileWriter3 = new FileWriter(file3,true); 
             BufferedWriter bufferedWriter3 = new BufferedWriter(fileWriter3);
                bufferedWriter3.newLine();
                bufferedWriter3.write(Topic_Area_Summary_Txt_Fld.getText());
                         bufferedWriter3.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(EducateX1v1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EducateX1v1.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_Done_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EducateX1v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EducateX1v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EducateX1v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EducateX1v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EducateX1v1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Tag_Btn;
    private javax.swing.JButton Done_Btn;
    private javax.swing.JComboBox<String> Tag_Item_Cmb_Bx;
    private javax.swing.JTextArea Topic_Area_Summary_Txt_Fld;
    private javax.swing.JTextField Topic_Question_Txt_Fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
